### ISSUE TITLE
Problem when fetching LOB objects

### ISSUE THREAD

**Issue by Jokero** [vietj/reactive-pg-client#12]
I have a table with LOB field. To fetch all records I execute the following query:
```
SELECT id, lo_get(big_object) as big_object FROM my_table
```
`big_object` is actually a serialised representation of `BigObject` class.

In order to iterate the whole table I'm trying to use a stream:
```
connection.prepare(sql) {
    val query = it.result()
    val tx = connection.begin()
    val stream = query.createStream(10, Tuple.tuple())

    stream.handler { row ->
        val id = row.getLong("id").toString()

        // here I'm trying to deserialise LOB into BigObject
        val filterByteArray = row.getBuffer("big_object").byteBuf.array()
        val byteArrayStream = ByteArrayInputStream(filterByteArray)
        val bigObject: BigObject = ObjectInputStream(byteArrayStream).readObject() as BigObject
    }
    stream.exceptionHandler { err ->
        println("Error ${err}")
    }
    stream.endHandler {
        tx.commit()
        println("End of stream")
    }
}
```
And this code actually works but only for the first `10` rows. It fails on 11th row with error:
```
java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:343)
	at io.netty.buffer.DuplicatedByteBuf.array(DuplicatedByteBuf.java:100)
	at io.netty.buffer.WrappedByteBuf.array(WrappedByteBuf.java:949)
```

If I increase batch size for example from `10` to `20` it will fail on 21th row. Exception is thrown at this place:
```
val filterByteArray = row.getBuffer("big_object").byteBuf.array() // where `array()` is called
```
If I print `row.getBuffer("big_object").byteBuf` to console we can see that in case of exception `byteBuf` has type of `PooledUnsafeDirectByteBuf` instead of `UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf`:
```
UnreleasableByteBuf(UnpooledDuplicatedByteBuf(ridx: 0, widx: 864, cap: 864, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 864, cap: 864))) // 10 times
UnreleasableByteBuf(UnpooledDuplicatedByteBuf(ridx: 0, widx: 864, cap: 864, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 864, cap: 864))) // case with exception
```

Maybe you know what could be the root cause of that error?

**Comment by BillyYccc** [comment]
Can you try `buffer.getBytes()` instead of using the ByteBuf `array()` method?

**Comment by Jokero** [comment]
Hmm. That was so simple. Thanks a ton! And sorry for bothering

**Comment by BillyYccc** [comment]
You're welcome.😄
