### ISSUE TITLE
Authentication type 10 is not supported in the client

### ISSUE THREAD

**Issue by luvarqpp** [vietj/reactive-pg-client#22]
When connecting to better secured postresql instances:
```
pgSubscriber.connect(ar -> {
      // ar.succeeded()) == false
      log.atError()
          .setMessage("pgSubscriber is not going to LISTEN to NOTIFY events!")
          .setCause(ar.cause())
          .addKeyValue("failed", ar.failed())
          .addKeyValue("cause.msg", (ar.cause() == null) ? "NULL" : ar.cause().getMessage())
          .log();
   });
````

```
java.lang.UnsupportedOperationException: Authentication type 10 is not supported in the client
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeAuthentication(MessageDecoder.java:369)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:150)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Seems that requested password encryption is not supported by this library.

**Comment by luvarqpp** [comment]
Seems that this library even does not have enum for request type 10. See:
https://github.com/vietj/reactive-pg-client/blob/master/src/main/java/io/reactiverse/pgclient/impl/codec/decoder/type/AuthenticationType.java

According to jdbc, given request type is perhaps SASL. See:
https://github.com/pgjdbc/pgjdbc/blob/5c9928d81e4a337518c1e1104ea17f4b29269320/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L98C47-L98C47
